version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user1
      - MONGO_INITDB_ROOT_PASSWORD=pass1
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=1
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    deploy:
      resources:
        limits:
          # cpus: '0.001'
          memory: 350M

  redis:
    image: redis:latest
    volumes:
      - redisdb:/data/db
    container_name: redis
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          # cpus: '0.001'
          memory: 150M





volumes:
  mongodb:
  redisdb: